title: GlueClaw
description: Claude Max provider for OpenClaw
remote_theme: just-the-docs/just-the-docs

color_scheme: light

search_enabled: true

aux_links:
  "GitHub":
    - "https://github.com/zeulewan/glueclaw"
  "X Post":
    - "https://x.com/zeulewan/status/2042769065408680223"
aux_links_new_tab: true

plugins:
  - jekyll-remote-theme
