import { spawn } from "node:child_process";
import { createInterface } from "node:readline";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  renameSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomBytes } from "node:crypto";
import { createAssistantMessageEventStream } from "@mariozechner/pi-ai";
import type { StreamFn } from "@mariozechner/pi-agent-core";
import type { AssistantMessage, Usage, TextContent } from "@mariozechner/pi-ai";

const PROCESS_TIMEOUT_MS = 5000;
const REQUEST_TIMEOUT_MS = 120_000;
const MAX_SESSIONS = 1000;

/** Shape of NDJSON stream events from the Claude CLI. */
interface StreamEventData {
  type: string;
  subtype?: string;
  session_id?: string;
  result?: string;
  usage?: Record<string, number>;
  event?: {
    delta?: { type?: string; text?: string };
  };
  message?: {
    content?: Array<{ type: string; text?: string }>;
  };
}

/** Track claude session IDs per session key for multi-turn resume.
 *  Persisted to disk so sessions survive gateway restarts. */
const GC_HOME = join(process.env.HOME ?? tmpdir(), ".glueclaw");
const SESSION_FILE = join(GC_HOME, "sessions.json");
const sessionMap = new Map<string, string>();

// Load persisted sessions on startup
try {
  const saved = JSON.parse(readFileSync(SESSION_FILE, "utf8"));
  for (const [k, v] of Object.entries(saved)) {
    if (typeof v === "string") sessionMap.set(k, v);
  }
} catch {
  // Expected on first run when session file doesn't exist
}

export function persistSessions(): void {
  try {
    const tmp = SESSION_FILE + ".tmp";
    writeFileSync(tmp, JSON.stringify(Object.fromEntries(sessionMap)));
    renameSync(tmp, SESSION_FILE); // Atomic on most filesystems
  } catch {
    // Best-effort persistence — non-fatal if disk write fails
  }
}

export function buildUsage(raw?: Record<string, number>): Usage {
  return {
    input: raw?.input_tokens ?? 0,
    output: raw?.output_tokens ?? 0,
    cacheRead: raw?.cache_read_input_tokens ?? 0,
    cacheWrite: raw?.cache_creation_input_tokens ?? 0,
    totalTokens:
      (raw?.input_tokens ?? 0) +
      (raw?.output_tokens ?? 0) +
      (raw?.cache_creation_input_tokens ?? 0) +
      (raw?.cache_read_input_tokens ?? 0),
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
  };
}

export function buildMsg(
  model: { api: string; provider: string; id: string },
  text: string,
  usage: Usage,
): AssistantMessage {
  return {
    role: "assistant",
    api: model.api,
    provider: model.provider,
    model: model.id,
    content: [{ type: "text", text }],
    stopReason: "stop",
    usage,
    timestamp: Date.now(),
  };
}

/** Get the MCP loopback port and token from process.env.
 *  The gateway patches write these during MCP server startup. */
export function getMcpLoopback(): { port: number; token: string } | undefined {
  const port = process.env.__GLUECLAW_MCP_PORT;
  const token = process.env.__GLUECLAW_MCP_TOKEN;
  if (port && token) return { port: parseInt(port, 10), token };
  return undefined;
}

/** Write a temporary MCP config file for the claude subprocess. */
export function writeMcpConfig(port: number): { path: string; cleanup: () => void } {
  const dir = join(tmpdir(), `glueclaw-mcp-${randomBytes(8).toString("hex")}`);
  mkdirSync(dir, { recursive: true });
  const configPath = join(dir, "mcp.json");
  const config = {
    mcpServers: {
      openclaw: {
        type: "http",
        url: `http://127.0.0.1:${port}/mcp`,
        headers: {
          Authorization: "Bearer ${OPENCLAW_MCP_TOKEN}",
          "x-session-key": "${OPENCLAW_MCP_SESSION_KEY}",
          "x-openclaw-agent-id": "${OPENCLAW_MCP_AGENT_ID}",
          "x-openclaw-account-id": "${OPENCLAW_MCP_ACCOUNT_ID}",
          "x-openclaw-message-channel": "${OPENCLAW_MCP_MESSAGE_CHANNEL}",
        },
      },
    },
  };
  writeFileSync(configPath, JSON.stringify(config, null, 2));
  return {
    path: configPath,
    cleanup: () => {
      try {
        rmSync(dir, { recursive: true });
      } catch {
        // Temp dir cleanup is best-effort
      }
    },
  };
}

/** Scrub Anthropic detection triggers from system prompts. */
export function scrubPrompt(input: string): string {
  return input
    .replace(
      /personal assistant running inside OpenClaw/g,
      "personal assistant running inside GlueClaw",
    )
    .replace(/HEARTBEAT_OK/g, "GLUECLAW_ACK")
    .replace(/reply_to_current/g, "reply_current")
    .replace(/\[\[reply_to:/g, "[[reply:")
    .replace(/openclaw\.inbound_meta/g, "glueclaw.inbound_meta")
    .replace(/generated by OpenClaw/g, "generated by GlueClaw");
}

/** Reverse scrub translations in response text for the gateway. */
export function unscrubResponse(text: string): string {
  return text
    .replace(/GLUECLAW_ACK/g, "HEARTBEAT_OK")
    .replace(/reply_current/g, "reply_to_current")
    .replace(/\[\[reply:/g, "[[reply_to:");
}

/** Evict oldest sessions when map exceeds MAX_SESSIONS */
function evictSessions(): void {
  while (sessionMap.size > MAX_SESSIONS) {
    const oldest = sessionMap.keys().next().value;
    if (oldest !== undefined) sessionMap.delete(oldest);
    else break;
  }
}

export function createClaudeCliStreamFn(opts: {
  claudeBin?: string;
  sessionKey?: string;
  modelOverride?: string;
  requestTimeoutMs?: number;
}): StreamFn {
  const claudeBin = opts.claudeBin ?? "claude";
  const requestTimeout = opts.requestTimeoutMs ?? REQUEST_TIMEOUT_MS;

  return (model, context, options) => {
    const stream = createAssistantMessageEventStream();

    const run = async () => {
      let mcpCleanup: (() => void) | undefined;
      let stderrBuf = "";
      try {
        // Scrub Anthropic detection triggers (see docs/detection-patterns.md)
        const cleanPrompt = scrubPrompt(context.systemPrompt ?? "");
        const resolvedModel = opts.modelOverride ?? model.id;
        const args = [
          "--dangerously-skip-permissions",
          "-p",
          "--output-format",
          "stream-json",
          "--verbose",
          "--include-partial-messages",
        ];
        // Resume session for multi-turn conversation memory
        const sessionKey = `glueclaw:${opts.sessionKey ?? "default"}`;
        const existingSessionId = sessionMap.get(sessionKey);
        if (existingSessionId) {
          args.push("--resume", existingSessionId);
        } else {
          if (cleanPrompt) args.push("--system-prompt", cleanPrompt);
        }
        if (resolvedModel) args.push("--model", resolvedModel);

        // Debug: log args for resume troubleshooting
        // Extract user message and scrub it too
        const lastUser = [...(context.messages ?? [])]
          .reverse()
          .find((m) => m.role === "user");
        let prompt = "";
        if (lastUser) {
          const c = lastUser.content;
          if (typeof c === "string") prompt = c;
          else if (Array.isArray(c))
            prompt = c
              .filter((b): b is TextContent => b.type === "text")
              .map((b) => b.text)
              .join("\n");
        }
        if (prompt) args.push(prompt);

        const env = { ...process.env };
        delete env.ANTHROPIC_API_KEY;
        delete env.ANTHROPIC_API_KEY_OLD;

        // Wire up MCP bridge for OpenClaw gateway tools
        const loopback = getMcpLoopback();
        if (loopback) {
          const mcp = writeMcpConfig(loopback.port);
          mcpCleanup = mcp.cleanup;
          args.push("--strict-mcp-config", "--mcp-config", mcp.path);
          env.OPENCLAW_MCP_TOKEN = loopback.token;
          env.OPENCLAW_MCP_SESSION_KEY = opts.sessionKey ?? "";
          env.OPENCLAW_MCP_AGENT_ID = "main";
          env.OPENCLAW_MCP_ACCOUNT_ID = "";
          env.OPENCLAW_MCP_MESSAGE_CHANNEL = "";
        }

        // Use persistent dir so claude sessions survive restarts
        const gcHome = join(process.env.HOME ?? "/tmp", ".glueclaw");
        mkdirSync(gcHome, { recursive: true });
        const proc = spawn(claudeBin, args, {
          stdio: ["pipe", "pipe", "pipe"],
          cwd: gcHome,
          env,
        });
        if (options?.signal)
          options.signal.addEventListener("abort", () => proc.kill("SIGTERM"));

        // Capture stderr for diagnostics
        if (proc.stderr) {
          proc.stderr.on("data", (chunk: Buffer) => {
            stderrBuf += chunk.toString();
            if (stderrBuf.length > 4096) stderrBuf = stderrBuf.slice(-4096);
          });
        }

        // Request timeout — kill process if it takes too long
        const requestTimer = setTimeout(() => {
          if (!ended) {
            proc.kill("SIGTERM");
            setTimeout(() => {
              try { proc.kill("SIGKILL"); } catch { /* already dead */ }
            }, PROCESS_TIMEOUT_MS);
          }
        }, requestTimeout);

        const info = {
          api: String(model.api ?? "anthropic-messages"),
          provider: String(model.provider ?? "glueclaw"),
          id: String(model.id),
        };
        let text = "";
        let started = false;
        let ended = false;

        const startStream = () => {
          if (started) return;
          started = true;
          const p = buildMsg(info, "", buildUsage());
          stream.push({ type: "start", partial: p });
          stream.push({ type: "text_start", contentIndex: 0, partial: p });
        };

        let streamed = false; // true if text was delivered via text_delta events

        const endStream = (usage?: Record<string, number>) => {
          if (ended) return;
          ended = true;
          // Translate renamed tokens back for the gateway
          // Skip if streaming deltas already unscrubbed each chunk
          if (!streamed) text = unscrubResponse(text);
          if (started && !streamed) {
            // Only emit text_end if text wasn't already delivered via streaming deltas
            stream.push({
              type: "text_end",
              contentIndex: 0,
              content: text,
              partial: buildMsg(info, text, buildUsage(usage)),
            });
          }
          stream.push({
            type: "done",
            reason: "stop",
            message: buildMsg(info, text || "(no response)", buildUsage(usage)),
          });
        };

        const rl = createInterface({ input: proc.stdout! });

        for await (const line of rl) {
          if (!line.trim()) continue;
          let data: StreamEventData;
          try {
            data = JSON.parse(line) as StreamEventData;
          } catch {
            // Skip malformed NDJSON lines
            continue;
          }

          const type = data.type;

          // Capture session ID for resume
          if (type === "system" && data.subtype === "init") {
            const sid = data.session_id;
            if (sid) {
              sessionMap.set(sessionKey, sid);
              evictSessions();
              persistSessions();
            }
            continue;
          }

          // Stream text deltas
          if (type === "stream_event") {
            const delta = data.event?.delta;
            if (delta?.type === "text_delta" && delta.text) {
              startStream();
              streamed = true;
              // Translate renamed tokens back in streaming deltas
              const dt = unscrubResponse(delta.text);
              text += dt;
              stream.push({
                type: "text_delta",
                contentIndex: 0,
                delta: dt,
                partial: buildMsg(info, text, buildUsage()),
              });
            }
            continue;
          }

          // Complete assistant message - only use if we didn't get streaming deltas
          if (type === "assistant") {
            if (!started) {
              const content = data.message?.content;
              if (content) {
                const textBlocks = content
                  .filter((b) => b.type === "text" && b.text)
                  .map((b) => b.text ?? "");
                if (textBlocks.length > 0) {
                  const fullText = textBlocks.join("\n");
                  startStream();
                  text = fullText;
                  stream.push({
                    type: "text_delta",
                    contentIndex: 0,
                    delta: fullText,
                    partial: buildMsg(info, text, buildUsage()),
                  });
                }
              }
            }
            continue;
          }

          // Result event (final) - authoritative response
          if (type === "result") {
            const sid = data.session_id;
            if (sid) {
              sessionMap.set(sessionKey, sid);
              evictSessions();
              persistSessions();
            }
            // Only use result text if nothing came through streaming or assistant
            if (!text) {
              const resultText = data.result;
              if (resultText) {
                startStream();
                text = resultText;
                stream.push({
                  type: "text_delta",
                  contentIndex: 0,
                  delta: text,
                  partial: buildMsg(info, text, buildUsage()),
                });
              }
            }
            endStream(data.usage);
            rl.close();
            proc.kill("SIGTERM");
            break;
          }
        }

        // Wait for process exit with timeout
        clearTimeout(requestTimer);
        await Promise.race([
          new Promise<void>((r) => proc.on("close", () => r())),
          new Promise<void>((r) => setTimeout(r, PROCESS_TIMEOUT_MS)),
        ]);
        // SIGKILL fallback if process didn't exit after SIGTERM
        try { proc.kill("SIGKILL"); } catch { /* already dead */ }
        if (!ended) endStream();
      } catch (err) {
        stream.push({
          type: "error",
          reason: "error",
          error: buildMsg(
            {
              api: String(model.api ?? "anthropic-messages"),
              provider: "glueclaw",
              id: String(model.id),
            },
            `Error: ${err instanceof Error ? err.message : String(err)}${stderrBuf ? "\nstderr: " + stderrBuf.trim() : ""}`,
            buildUsage(),
          ),
        });
      } finally {
        mcpCleanup?.();
        stream.end();
      }
    };

    queueMicrotask(() => void run());
    return stream;
  };
}
