import { describe, it, expect, afterEach } from "vitest";
import {
  buildUsage,
  buildMsg,
  scrubPrompt,
  unscrubResponse,
  getMcpLoopback,
} from "../../stream.js";
import { MODEL_CATALOG } from "../../catalog.js";
import { binarySearchTrigger } from "../../healthcheck.js";
import { resolveSessionKey } from "../../session-key.js";

describe("buildUsage", () => {
  it("returns zeroed usage when called with undefined", () => {
    const usage = buildUsage();
    expect(usage.input).toBe(0);
    expect(usage.output).toBe(0);
    expect(usage.cacheRead).toBe(0);
    expect(usage.cacheWrite).toBe(0);
    expect(usage.totalTokens).toBe(0);
  });

  it("maps raw token fields correctly", () => {
    const raw = {
      input_tokens: 100,
      output_tokens: 50,
      cache_read_input_tokens: 25,
      cache_creation_input_tokens: 10,
    };
    const usage = buildUsage(raw);
    expect(usage.input).toBe(100);
    expect(usage.output).toBe(50);
    expect(usage.cacheRead).toBe(25);
    expect(usage.cacheWrite).toBe(10);
  });

  it("totalTokens equals the sum of all four fields", () => {
    const raw = {
      input_tokens: 100,
      output_tokens: 50,
      cache_read_input_tokens: 25,
      cache_creation_input_tokens: 10,
    };
    const usage = buildUsage(raw);
    expect(usage.totalTokens).toBe(185);
  });

  it("cost is always zero (Max subscription)", () => {
    const raw = { input_tokens: 1000, output_tokens: 500 };
    const usage = buildUsage(raw);
    expect(usage.cost).toEqual({
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
      total: 0,
    });
  });

  it("handles partial raw object with missing fields", () => {
    const raw = { input_tokens: 42 };
    const usage = buildUsage(raw);
    expect(usage.input).toBe(42);
    expect(usage.output).toBe(0);
    expect(usage.cacheRead).toBe(0);
    expect(usage.cacheWrite).toBe(0);
    expect(usage.totalTokens).toBe(42);
  });
});

describe("buildMsg", () => {
  const model = {
    api: "anthropic-messages",
    provider: "glueclaw",
    id: "glueclaw-opus",
  };
  const usage = buildUsage();

  it("returns correct shape", () => {
    const msg = buildMsg(model, "hello", usage);
    expect(msg.role).toBe("assistant");
    expect(msg.api).toBe("anthropic-messages");
    expect(msg.provider).toBe("glueclaw");
    expect(msg.model).toBe("glueclaw-opus");
    expect(msg.stopReason).toBe("stop");
  });

  it("content is [{ type: 'text', text }]", () => {
    const msg = buildMsg(model, "hello world", usage);
    expect(msg.content).toEqual([{ type: "text", text: "hello world" }]);
  });

  it("timestamp is approximately Date.now()", () => {
    const before = Date.now();
    const msg = buildMsg(model, "test", usage);
    const after = Date.now();
    expect(msg.timestamp).toBeGreaterThanOrEqual(before);
    expect(msg.timestamp).toBeLessThanOrEqual(after);
  });

  it("passes usage through unchanged", () => {
    const custom = buildUsage({ input_tokens: 99, output_tokens: 1 });
    const msg = buildMsg(model, "x", custom);
    expect(msg.usage.input).toBe(99);
    expect(msg.usage.output).toBe(1);
  });
});

describe("scrubPrompt", () => {
  it("replaces 'personal assistant running inside OpenClaw'", () => {
    const input = "You are a personal assistant running inside OpenClaw.";
    expect(scrubPrompt(input)).toBe(
      "You are a personal assistant running inside GlueClaw.",
    );
  });

  it("replaces HEARTBEAT_OK", () => {
    expect(scrubPrompt("token: HEARTBEAT_OK")).toBe("token: GLUECLAW_ACK");
  });

  it("replaces reply_to_current", () => {
    expect(scrubPrompt("action: reply_to_current")).toBe(
      "action: reply_current",
    );
  });

  it("replaces [[reply_to:", () => {
    expect(scrubPrompt("use [[reply_to:user]]")).toBe("use [[reply:user]]");
  });

  it("replaces openclaw.inbound_meta", () => {
    expect(scrubPrompt("field: openclaw.inbound_meta")).toBe(
      "field: glueclaw.inbound_meta",
    );
  });

  it("replaces 'generated by OpenClaw'", () => {
    expect(scrubPrompt("This was generated by OpenClaw")).toBe(
      "This was generated by GlueClaw",
    );
  });

  it("handles empty string", () => {
    expect(scrubPrompt("")).toBe("");
  });

  it("passes through text with no triggers", () => {
    const safe = "Just a normal prompt with no detection patterns.";
    expect(scrubPrompt(safe)).toBe(safe);
  });

  it("handles multiple triggers in one string", () => {
    const input =
      "personal assistant running inside OpenClaw with HEARTBEAT_OK and reply_to_current";
    const expected =
      "personal assistant running inside GlueClaw with GLUECLAW_ACK and reply_current";
    expect(scrubPrompt(input)).toBe(expected);
  });

  it("does not modify file paths containing 'openclaw'", () => {
    const path = "~/.openclaw/config.json";
    expect(scrubPrompt(path)).toBe(path);
  });

  it("does not modify URLs containing 'openclaw'", () => {
    const url = "https://openclaw.example.com/api";
    expect(scrubPrompt(url)).toBe(url);
  });

  it("replaces multiple occurrences of the same trigger", () => {
    const input = "HEARTBEAT_OK and also HEARTBEAT_OK";
    expect(scrubPrompt(input)).toBe("GLUECLAW_ACK and also GLUECLAW_ACK");
  });
});

describe("unscrubResponse", () => {
  it("reverses GLUECLAW_ACK to HEARTBEAT_OK", () => {
    expect(unscrubResponse("token: GLUECLAW_ACK")).toBe("token: HEARTBEAT_OK");
  });

  it("reverses reply_current to reply_to_current", () => {
    expect(unscrubResponse("action: reply_current")).toBe(
      "action: reply_to_current",
    );
  });

  it("reverses [[reply: to [[reply_to:", () => {
    expect(unscrubResponse("use [[reply:user]]")).toBe("use [[reply_to:user]]");
  });

  it("handles empty string", () => {
    expect(unscrubResponse("")).toBe("");
  });

  it("passes through text with no scrubbed tokens", () => {
    const text = "Just a normal response.";
    expect(unscrubResponse(text)).toBe(text);
  });

  it("handles multiple tokens in one string", () => {
    const input = "GLUECLAW_ACK with reply_current and [[reply:x]]";
    const expected = "HEARTBEAT_OK with reply_to_current and [[reply_to:x]]";
    expect(unscrubResponse(input)).toBe(expected);
  });
});

describe("getMcpLoopback", () => {
  const origPort = process.env.__GLUECLAW_MCP_PORT;
  const origToken = process.env.__GLUECLAW_MCP_TOKEN;

  afterEach(() => {
    if (origPort !== undefined) process.env.__GLUECLAW_MCP_PORT = origPort;
    else delete process.env.__GLUECLAW_MCP_PORT;
    if (origToken !== undefined) process.env.__GLUECLAW_MCP_TOKEN = origToken;
    else delete process.env.__GLUECLAW_MCP_TOKEN;
  });

  it("returns { port, token } when both env vars set", () => {
    process.env.__GLUECLAW_MCP_PORT = "3456";
    process.env.__GLUECLAW_MCP_TOKEN = "secret123";
    const result = getMcpLoopback();
    expect(result).toEqual({ port: 3456, token: "secret123" });
  });

  it("returns undefined when port is missing", () => {
    delete process.env.__GLUECLAW_MCP_PORT;
    process.env.__GLUECLAW_MCP_TOKEN = "secret123";
    expect(getMcpLoopback()).toBeUndefined();
  });

  it("returns undefined when token is missing", () => {
    process.env.__GLUECLAW_MCP_PORT = "3456";
    delete process.env.__GLUECLAW_MCP_TOKEN;
    expect(getMcpLoopback()).toBeUndefined();
  });

  it("returns undefined when both are missing", () => {
    delete process.env.__GLUECLAW_MCP_PORT;
    delete process.env.__GLUECLAW_MCP_TOKEN;
    expect(getMcpLoopback()).toBeUndefined();
  });

  it("parses port as integer", () => {
    process.env.__GLUECLAW_MCP_PORT = "8080";
    process.env.__GLUECLAW_MCP_TOKEN = "tok";
    const result = getMcpLoopback();
    expect(result?.port).toBe(8080);
    expect(typeof result?.port).toBe("number");
  });
});

describe("MODEL_CATALOG", () => {
  it("has exactly 3 entries", () => {
    expect(MODEL_CATALOG).toHaveLength(3);
  });

  it("every entry has required fields: id, name, provider, contextWindow", () => {
    for (const entry of MODEL_CATALOG) {
      expect(entry.id).toBeTruthy();
      expect(entry.name).toBeTruthy();
      expect(entry.provider).toBeTruthy();
      expect(entry.contextWindow).toBeGreaterThan(0);
    }
  });

  it("every entry has input array containing 'text'", () => {
    for (const entry of MODEL_CATALOG) {
      expect(entry.input).toEqual(expect.arrayContaining(["text"]));
    }
  });

  it("opus and sonnet have reasoning: true", () => {
    const opus = MODEL_CATALOG.find((m) => m.id.includes("opus"));
    const sonnet = MODEL_CATALOG.find((m) => m.id.includes("sonnet"));
    expect(opus?.reasoning).toBe(true);
    expect(sonnet?.reasoning).toBe(true);
  });

  it("all provider fields match 'glueclaw'", () => {
    for (const entry of MODEL_CATALOG) {
      expect(entry.provider).toBe("glueclaw");
    }
  });
});

describe("binarySearchTrigger", () => {
  it("returns the offending line when trigger is in first half", async () => {
    const lines = ["safe line 1", "BADWORD here", "safe line 3", "safe line 4"];
    const testFn = async (chunk: string) => !chunk.includes("BADWORD");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("BADWORD here");
  });

  it("returns the offending line when trigger is in second half", async () => {
    const lines = [
      "safe line 1",
      "safe line 2",
      "safe line 3",
      "TRIGGER at end",
    ];
    const testFn = async (chunk: string) => !chunk.includes("TRIGGER");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("TRIGGER at end");
  });

  it("returns null when entire prompt passes", async () => {
    const lines = ["safe line 1", "safe line 2", "safe line 3"];
    const testFn = async () => true;
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBeNull();
  });

  it("narrows to single line containing the trigger", async () => {
    const lines = Array.from({ length: 20 }, (_, i) =>
      i === 13 ? "line13bad" : `safe line ${i}`,
    );
    const testFn = async (chunk: string) => !chunk.includes("line13bad");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("line13bad");
  });

  it("calls testFn O(log n) times, not O(n)", async () => {
    let callCount = 0;
    const lines = Array.from({ length: 100 }, (_, i) =>
      i === 50 ? "hidden-trigger" : `safe line ${i}`,
    );
    const testFn = async (chunk: string) => {
      callCount++;
      return !chunk.includes("hidden-trigger");
    };
    await binarySearchTrigger(lines, testFn);
    // log2(100) ≈ 7, plus initial full-prompt test and some overhead
    expect(callCount).toBeLessThan(20);
  });

  it("handles single-line input that triggers", async () => {
    const testFn = async (chunk: string) => !chunk.includes("X");
    const result = await binarySearchTrigger(["X"], testFn);
    expect(result).toBe("X");
  });

  it("handles empty input", async () => {
    const testFn = async () => true;
    const result = await binarySearchTrigger([], testFn);
    expect(result).toBeNull();
  });

  it("handles trigger on the first line", async () => {
    const lines = ["TRIGGER", "safe", "safe", "safe"];
    const testFn = async (chunk: string) => !chunk.includes("TRIGGER");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("TRIGGER");
  });

  it("handles trigger on the last line", async () => {
    const lines = ["safe", "safe", "safe", "TRIGGER"];
    const testFn = async (chunk: string) => !chunk.includes("TRIGGER");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("TRIGGER");
  });
});

describe("resolveSessionKey", () => {
  it("prefers sessionKey over everything else", () => {
    expect(
      resolveSessionKey({
        sessionKey: "telegram:dm:+34xxx",
        sessionId: "abc-uuid",
        agentDir: "/home/x/.openclaw/agents/eva",
      }),
    ).toBe("telegram:dm:+34xxx");
  });

  it("falls back to sessionId when sessionKey is absent", () => {
    expect(
      resolveSessionKey({
        sessionId: "conv-uuid-1",
        agentDir: "/home/x/.openclaw/agents/eva",
      }),
    ).toBe("conv-uuid-1");
  });

  it("falls back to agentDir when sessionKey and sessionId are absent", () => {
    expect(
      resolveSessionKey({
        agentDir: "/home/x/.openclaw/agents/eva",
      }),
    ).toBe("/home/x/.openclaw/agents/eva");
  });

  it("falls back to 'default' when nothing is provided", () => {
    expect(resolveSessionKey({})).toBe("default");
  });

  it("yields distinct keys for two conversations of the same agent (the bug fix)", () => {
    const agentDir = "/home/x/.openclaw/agents/eva";
    const a = resolveSessionKey({
      sessionKey: "telegram:dm:userA",
      agentDir,
    });
    const b = resolveSessionKey({
      sessionKey: "telegram:dm:userB",
      agentDir,
    });
    expect(a).not.toBe(b);
  });

  it("yields the same key across turns of one conversation (resumption stability)", () => {
    const ctx = {
      sessionKey: "telegram:group:abc:user:def",
      sessionId: "rotating-uuid-on-reset",
      agentDir: "/home/x/.openclaw/agents/eva",
    };
    expect(resolveSessionKey(ctx)).toBe(resolveSessionKey(ctx));
  });

  it("treats empty string as a valid value (does not skip to fallback)", () => {
    // Empty strings are unlikely in practice but we should not silently
    // collapse them — only undefined triggers fallback.
    expect(
      resolveSessionKey({
        sessionKey: "",
        sessionId: "would-be-skipped",
      }),
    ).toBe("would-be-skipped");
  });
});
